name: reviewdog
on: [pull_request]

jobs:
  checkstyle:
    name: Checkstyle with reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Checkstyle
        run: ./gradlew check

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run reviewdog for main
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
        run: cat ./build/reports/checkstyle/main.xml |
          reviewdog -f=checkstyle -name="checkstyle" -reporter="github-pr-review"

      - name: Run reviewdog for test
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
        run: cat ./build/reports/checkstyle/test.xml |
          reviewdog -f=checkstyle -name="checkstyle" -reporter="github-pr-review"
